
version: "3.9"
services:
  ### PostgreSQL Database
  postgres:
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orion
    image: postgres:latest
    volumes:
      - $HOME/database:/var/lib/postgresql
    ports:
      - 5432:5432

  ### Prefect Server
  orion:
    image: prefecthq/prefect:2-python3.10
    restart: always
    volumes:
      - .prefect:/root/.prefect
    entrypoint: ["prefect", "server", "start","--log-level", "DEBUG", "--host", "0.0.0.0"]
    environment:
      - PREFECT_ORION_API_HOST=0.0.0.0
      - PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/orion
    ports:
      - 4200:4200
    depends_on:
      - postgres

  ### Jupyterlab development environment (comment out if not needed)
  dev_container:
    image: user/bar
    ports:
      - 8080:8080
    build:
      context: ./images/dev
      dockerfile: Dockerfile
    entrypoint: ["jupyter", "lab","--ip=0.0.0.0", "--port=8080","--allow-root"]
    volumes:
      - $PWD:/root/project

