dev_profile:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'database'
      schema: 'main'
      schemas_and_paths:
        main: 'C:\Users\B081267\Documents\python\grid_app\db\database.db'
      schema_directory: 'C:\Users\B081267\Documents\python\grid_app\db'
